Newsweek-Bootstrap
Diegodsha/Newsweek-Bootstrap pull request #1
Opened 2021-01-25 23:12 UTC by Diegodsha

2021-01-26 07:03 UTC, jubaan requested changes
# Status: Approved with OBSERVATIONS :recycle: 

## :wave: :wave: Hello @Diegodsha and @EroAuditore  . Thanks for submitting you project!

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] The PR should have a descriptive message, a summary of the features, and things worth mentioning about the project.
- [ ] Feature branch should use a descriptive and meaningful name. Example `newsweek-clone`.
- [ ] Commit messages should be meaningful and descriptive. Example `Add navbar feature`, `Merge navbar-prototype with newsweek-clone branch`, `Update contact info in README`.
- [ ] The live preview link in README is broken.
- [x] The MIT license link takes to a Wikipedia page that explains the MIT license. Please create your MIT LIcense file and link it in the REAME.
- [x] Change the social media handlers to the actual username. Example: #BAD [@githubhandle](#) #GOOD [@jubaan](https://www.github.com/jubaan)
- [ ] The preview screenshot is not displaying in the README
- [ ] Wrap the `<header>` with semantic HTML
- [ ] See inline comments for `index.html` and stylesheet files.
- [ ] Navbar
  - [ ] DESKTOP view
    - [ ] the date the logo and login and subscribe elements are not aligned as the original design. They should be vertically aligned to the end or bottom in line with the bottom of the letter in the newsweek logo.
    - [ ] The subscribe link should have a space to the right so it doesn't touch the border of the screen.
    - [ ] The search and its icon should be part of the same element.
    - [ ] The navbar has a margin-top that creates a white space between the navbar and the top of the browser.  
    - [ ] the navbar logo has a different background color that dont' match the design. Please try to find in the original website the svg image.
    ![image](https://user-images.githubusercontent.com/25774518/105808930-56aaaf80-5f6e-11eb-9677-177cc0e29a51.png)
  - [ ] MOBILE view
    - [ ] elements are not equally spaced to the margins
    ![image](https://user-images.githubusercontent.com/25774518/105810516-b609bf00-5f70-11eb-9109-f0a63820434a.png)

- [ ] Footer
  - [ ] DESKTOP
    - [ ] logo, copyright and social media icons are not aligned correctly, vertically and horizontally.
    - [ ] Editions section is taking another row to display the information, all should be in the same line
    - [ ] Logo, editions section and about us section should all be aligned equally to the left
  ![image](https://user-images.githubusercontent.com/25774518/105810819-3e885f80-5f71-11eb-9ffd-43517fc93052.png)
  - [ ] TABLET and MOBILE views
    - [ ] The same applies for the tablet and mobile views
  ![image](https://user-images.githubusercontent.com/25774518/105811109-b9ea1100-5f71-11eb-9240-7e7f6d624667.png)
  ![image](https://user-images.githubusercontent.com/25774518/105811184-d25a2b80-5f71-11eb-8a27-a0ac8edc295c.png)

**NOTE**: the milestone should appear as approved in your Microverse progress dashboard, this doesn't mean that you shouldn't work on fixing the previous observations, so please work on them before moving to the next milestone. If you don't do it, observations will pile up on Milestone 3.





## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2021-01-26 07:03 UTC, jubaan commented on index.html
> +          <div class="subscribe-btn btn btn-primary col-8">SUBSCRIBE ></div>
- [x] Login, Login icon, and subscribe should use semantic HTML. They at as link or `<a>` tags on the original desing.

2021-01-26 07:03 UTC, jubaan commented on index.html
> +              <img class="logo-img" src="assets/Newsweek_Logo.svg" alt="logo" />
- [x] Logo both int header and footer should be links with `<a>` anchor semantic HTML

2021-01-26 07:03 UTC, jubaan commented on index.html
> +            <li><a class="text-muted fw-400" href="#">Search</a></li>
- [x] Search should use a form with a search input.

2021-01-26 07:03 UTC, jubaan commented on index.html
> +        <li>Rumania</li>
- [x] These elements should be links

2021-01-26 07:03 UTC, jubaan commented on index.html
> +        <li>Announcements</li>
- [x] Also these elements should be links

2021-01-26 07:03 UTC, jubaan commented on styles/desktop.css
> +  color: #fff;
- [x] Use bootstrap classes to minimize custom CSS stylesheets.
  - [x] This applies for text-colors, font-weights, list-style, borders, text-decoration, padding, margin, display flex.
  - [x] Review all stylesheets and look for these elements remove them from the custom CSS and adapt them with Bootstrap classes, the ones that apply.
  - [x] Review `desktop.css`, `mobile.ccs`, `style.css`, and `tablet.css` files.
  - [x] Also eliminate Duplicated code to keep the Stylesheets DRY and clean, to give an example of repeated code. `color: #fff` is repeated numerous times through the stylesheets. `padding-left:20`, `font-size: 18px`, and others. There are various ways to tackle this issue, by generating utility CSS classes, by grouping all elements that use the same rule and for some create global rules that apply to all elements.

2021-01-27 03:58 UTC, PhillipUg requested changes
Hey team, 👋

You have done an amazing job implementing the requirements for this project.

However, there are still some changes 👇 you need to implement to approve this request 🔍

### Changes Required ♻️ 

- [ ] You're supposed to use Bootstrap CSS classes **everywhere** for styling (for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options)). The main goal of this project is to learn how to **use the Bootstrap framework**, specifically its responsive design features: you should focus on this aspect as you work on your project. That being said, use bootstrap to replace most of your media queries and other classes in your `style.css`. 

#### Please note that this request will be approved in the dashboard and you don’t need to submit it for re-review or merge this request into the main branch please make the suggested changes and move on to the next milestone. When you're done with the next milestone, submit this request again, don't create a new pull request. You are to keep submitting this same pull request until project completion.

If you have any questions, feel free to send me a message through Slack as **Phillip Musiime** or
 <a href="mailto:phillipmusiime@gmail.com"> <img alt="gmail" src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social" target="_blank"></a> &nbsp; &nbsp; [![Twitter Follow](https://img.shields.io/twitter/follow/Phillip_Ug?style=social)](https://twitter.com/intent/follow?screen_name=Phillip_Ug) &nbsp; &nbsp; [![GitHub followers](https://img.shields.io/github/followers/phillipug?label=Follow&style=social)](https://github.com/PhillipUg)

2021-01-28 04:28 UTC, euqueme requested changes
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)
### Hello @Diegodsha and @EroAuditore :lollipop: :balloon:  

### Thank you for your submission :handshake: your project looks amazing :astonished: is almost like the original :star_struck: claps for the great work done so far :clap: :clap: :clap: let's make the following changes :construction_worker: 

### General

- [ ] Use [semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp)
> make use of the aside tag for the sections below the editor's picks.

### Implementation requirements

* [ ] Use Bootstrap CSS classes **everywhere** for styling (for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options))

> I've put comments directly in the CSS file, where you should use bootstrap classes and the CSS files should be as small as possible

### All Milestone requirements

#### Mobile Screens

##### TOP STORY
- [ ] This should be the first section showing in this screen size this is usually achievable with the `flex-column-reverse` bootstrap class
Clone
![image](https://user-images.githubusercontent.com/52209067/106086669-3bfc4600-60e8-11eb-9e33-7255f467746b.png)
Original
![image](https://user-images.githubusercontent.com/52209067/106086707-50d8d980-60e8-11eb-9d54-a6c1d1b066e4.png)
##### Main news sections (U.S., World, etc.)
- [ ] The images of the small articles should take 60% of the screen width
- Clone
![image](https://user-images.githubusercontent.com/52209067/106086941-aca36280-60e8-11eb-9483-5195829170c1.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/106070063-5c68d800-60c9-11eb-86d6-e61d0d58740d.png)
##### SUBSCRIBE
- [ ] The images, text and subscribe button should be centered and the bold text should be on top of the images
- Clone
![image](https://user-images.githubusercontent.com/52209067/106087171-0e63cc80-60e9-11eb-8c35-28ccffc09359.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/106070333-e31db500-60c9-11eb-8ef9-210903ab4d0a.png)
##### NEWSLEETTER
- [ ] The text should be centered, and the container that holds the text, email input field and FREE SIGN UP button should have a gray border
- Clone
![image](https://user-images.githubusercontent.com/52209067/106087347-6ac6ec00-60e9-11eb-9e8b-aaf438da5b92.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/106072842-8a9ce680-60ce-11eb-8fd0-dacf10a73207.png)
##### Footer
- [ ] The  last 3 rows with links should also have a white background and should be aligned  with the Newsweek logo and social media icons
- Clone
![image](https://user-images.githubusercontent.com/52209067/106087599-f6407d00-60e9-11eb-8f38-de2112adf614.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/106073120-1282f080-60cf-11eb-83cb-a298b8f52266.png)
#### Tablet Screens
##### NEWSLETTER
- [ ] The text should be centered
Clone
![image](https://user-images.githubusercontent.com/52209067/106089040-b9c25080-60ec-11eb-82aa-90eea2bf577c.png)
Original
![image](https://user-images.githubusercontent.com/52209067/106089060-c5ae1280-60ec-11eb-9b58-e673c37a35fa.png)
##### Footer
- [ ] The footer should have less margin on the left and right in comparison with the upper sections
Clone
![image](https://user-images.githubusercontent.com/52209067/106089153-fdb55580-60ec-11eb-8a38-f0419427a08c.png)
Original
![image](https://user-images.githubusercontent.com/52209067/106089179-0c9c0800-60ed-11eb-9a0e-e080fb0b7d7e.png)
#### Desktop Screens
##### SUBSCRIBE and NEWSLETTER
- [ ] should have more margin on the left and right in comparison with the Footer
Clone
![image](https://user-images.githubusercontent.com/52209067/106089523-b67b9480-60ed-11eb-84bf-6cc340eb3dd7.png)
Original
![image](https://user-images.githubusercontent.com/52209067/106089557-c8f5ce00-60ed-11eb-92b2-0b83a8830d63.png)
#### All screen sizes
##### Column 2 and 3
* [ ] Each image have a link
* [ ] Each title uses a hx tag and have a link
> All the images starting from MY TURN on column 2 to OPINIONS on column 3 are missing these let's fix them.

### That's it, team!  :raised_hands: 
### Please :pray:  do the changes :technologist: :technologist:  and submit back for a code review when you are done :memo: 
Any question? ask me on slack **@ Maru** :woman_technologist: 
### Happy coding! :rocket: 
PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2021-01-28 04:28 UTC, euqueme commented on styles/desktop.css
> +  color: #000;
- [x] Use bootstrap classes for basic colors (like white, black or red)

2021-01-28 04:28 UTC, euqueme commented on styles/desktop.css
> +  font-weight: bold;
- [x] Theres a bootstrap class for font-weight let's use it

2021-01-28 04:28 UTC, euqueme commented on styles/desktop.css
> +  list-style: none;
- [x] Use the bootstrap class for `list-style: none`

2021-01-28 04:28 UTC, euqueme commented on styles/desktop.css
> +  text-decoration: none;
- [x] Use the bootstrap class for `text-decoration: none`

2021-01-28 04:28 UTC, euqueme commented on styles/desktop.css
> +  color: #000;
- [x] Use bootstrap classes for basic colors (like white, black or red)

2021-01-28 04:28 UTC, euqueme commented on styles/desktop.css
> +  color: #000;
- [x] Use bootstrap classes for basic colors (like white, black or red)

2021-01-28 04:28 UTC, euqueme commented on styles/desktop.css
> +  text-decoration: none;
- [x] Use the bootstrap class for `text-decoration: none`

2021-01-28 04:28 UTC, euqueme commented on styles/style.css
> +  text-decoration: none;
- [x] Use the bootstrap class for `text-decoration: none`

2021-01-28 04:28 UTC, euqueme commented on styles/style.css
> +  text-decoration: none;
- [x] Use the bootstrap class for `text-decoration: none`

2021-01-28 04:28 UTC, euqueme commented on styles/style.css
> +  text-decoration: none;
- [x] Use the bootstrap class for `text-decoration: none`

2021-01-28 04:28 UTC, euqueme commented on styles/mobile.css
> +  color: #000;
- [x] Use bootstrap classes for basic colors (like white, black or red)

2021-01-28 04:28 UTC, euqueme commented on styles/style.css
> +  color: #000;
- [x] Use bootstrap classes for basic colors (like white, black or red)

2021-01-28 04:28 UTC, euqueme commented on styles/style.css
> +  color: #000;
- [x] Use bootstrap classes for basic colors (like white, black or red)

2021-01-28 04:28 UTC, euqueme commented on styles/tablet.css
> +  color: #000;
- [x] Use bootstrap classes for basic colors (like white, black or red)

2021-01-28 04:28 UTC, euqueme commented on styles/style.css
> +  display: flex;
- [x] Use bootstrap classes for `display`

2021-01-28 04:28 UTC, euqueme commented on styles/style.css
> +  display: flex;
- [x] Use bootstrap classes for `display`

2021-01-28 04:28 UTC, euqueme commented on styles/style.css
> +  display: block;
- [x] Use bootstrap classes for `display`

2021-01-28 04:28 UTC, euqueme commented on styles/style.css
> +  position: sticky;
- [x] Use the bootstrap class for `position: sticky`

2021-01-28 04:28 UTC, euqueme commented on styles/style.css
> +  text-transform: uppercase;
- [x] Use the bootstrap class for text-transform

2021-01-28 04:28 UTC, euqueme commented on styles/style.css
> +  text-align: center;
- [x] Use the bootstrap class for text-align

2021-01-28 04:28 UTC, euqueme commented on styles/style.css
> +  position: relative;
- [x] Use the bootstrap class for `position`

2021-01-28 04:28 UTC, euqueme commented on styles/style.css
> +  position: absolute;
- [x] Use the bootstrap class for `position`

2021-01-28 04:28 UTC, euqueme commented on styles/style.css
> +  position: relative;
- [x] Use the bootstrap class for `position`

2021-01-28 04:28 UTC, euqueme commented on styles/style.css
> +  position: absolute;
- [x] Use the bootstrap class for `position`

2021-01-29 01:10 UTC, voscarmv requested changes
# Impressive work, team. 💻 👀 ✨ 

- Your project is almost perfect. Excellent work applying Maru's requested changes.

## However, there are some changes required 👀 🧰 🔨 🔧 
- On Desktop view, the images of your in-magazine section are distorted. Please fix this:
![image](https://user-images.githubusercontent.com/2739245/106216638-3874c780-6199-11eb-9c78-98579ed00b38.png)

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-01-29 15:38 UTC, PhillipUg approved these changes
# Status: Project Approved! 🥇 
Congratulations on implementing all requirements and getting this project approved. :+1:

You can merge this branch into the main branch when you're ready and go on to your next project.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime** or
 <a href="mailto:phillipmusiime@gmail.com"> <img alt="gmail" src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social" target="_blank"></a> &nbsp; &nbsp; [![Twitter Follow](https://img.shields.io/twitter/follow/Phillip_Ug?style=social)](https://twitter.com/intent/follow?screen_name=Phillip_Ug) &nbsp; &nbsp; [![GitHub followers](https://img.shields.io/github/followers/phillipug?label=Follow&style=social)](https://github.com/PhillipUg)

2021-01-29 16:17 UTC, merged